# Generated by Django 5.2.8 on 2025-12-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userfile_public_link_userfile_public_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='public_link',
        ),
    ]
