# Generated by Django 5.2.8 on 2026-01-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userfile_public_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userfile',
            name='public_access_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfile',
            name='public_access_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
